DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS person;

CREATE TABLE person
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) CHECK (LENGTH(full_name) >= 10 AND LENGTH(full_name) <= 100) UNIQUE NOT NULL,
    year_of_birth INT CHECK (year_of_birth >= 1900)                                                NOT NULL
);

CREATE TABLE book
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT                      REFERENCES person (id) ON DELETE SET NULL,
    title    VARCHAR(100)             NOT NULL,
    author   VARCHAR(100)             NOT NULL,
    year     INT CHECK (year >= 1500) NOT NULL
);

